Add flag to close cmake window after successful build and call autocommand events
cdelledonne/vim-cmake pull request #7
Opened 2020-08-13 08:45 UTC by AlexAUT

Implemented a flag to close the window after a successful build.
I also added autocommand events after a build fails/succeeds. However, I'm not sure I did it the right way (group user)

2020-08-20 16:28 UTC, cdelledonne commented
Hey, thanks for picking this up. I have a couple of comments:

1. I would prefer to introduce one feature at a time. In this case, either an option to close the CMake window after successful build, or User autocommands. I would prefer the latter, as it provides more flexibility, and can be used to close the window as well as any other thing (as you pointed out in #7).

2. For User autocommands, I would prefer to have a new section in `doc/cmake.txt`, e.g. between "Mappings" and "Configuration", which we could call "Events". We could also add one or two examples in there. Remember to run `vim -u NONE -c "helptags doc | q"` after adding new tags to the docs.

3. From `:help <nomodeline>`:
    > After applying the autocommands the modelines are processed, so that their settings overrule the settings from autocommands when editing a file. This is skipped if <nomodeline> is specified. You probably want to use <nomodeline> for events not used when loading a buffer, such as User. Modelines are also skipped when no matching autocommands were executed.

    This makes me think that we should to `doautocmd <nomodeline> User ...`

4. The events `CMakeBuildFailed` and `CMakeBuildSucceeded` should only trigger when calling `:CMakeBuild`, and not `:CMakeGenerate`, right?

5. Could you also update the CHANGELOG? I forgot to add this step inside CONTRIBUTING.md, will do that soon.

Looking forward to your updates, and thanks again!

2020-09-02 07:16 UTC, AlexAUT commented
Sorry for the late reply, I'm currently moving. I will implement your feedback this weekend.

2020-09-02 08:07 UTC, cdelledonne commented
No problem, take your time.

By the way, you might want to rebase onto `master` before proceeding. And regarding the examples in the docs, you could show how to jump to the first error in case of a `CMakeBuildFailed` (e.g. using the quickfix command `:cfirst`).

Thanks again!

2020-11-02 08:46 UTC, cdelledonne commented
Hi, do you still plan to work on this? Just checking.

2020-11-19 13:44 UTC, AlexAUT commented
Hi, sorry the PR got lost after I was moving. I will adjust it during the next few days.

2020-11-19 15:39 UTC, AlexAUT commented
@cdelledonne: I only kept the autocmd and adjusted the docs based on your feedback above

2020-11-19 17:37 UTC, cdelledonne requested changes
Thanks a lot for picking this up again. I have a few more style comments to be addressed, sorry for being picky on that.

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +Events							*cmake-events*
Please capitalize "EVENTS" for consistency with other sections

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +To customize behaviour after a command has finished, Vim-CMake calls user
I would slightly edit this into

To customize *the* behaviour after a *`:CMakeBuild`* command has finished, Vim-CMake *defines some* user *events*.

(the words in italics are just to point at the changes)

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +List of events~
Not really needed

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +CMakeBuildFailed
Please format like e.g. the Global <Plug> Mappings, i.e. event name on the left, and small description on the right (indented like in the <Plug> Mappings as well)

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +Example usage of CMakeBuildFailed to jump to the first error
Please wrap CMakeBuildFailed in backticks

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +      let g:jump_on_error = 0 " We do not want to focus the console
Indent all lines with a single tab character please

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +
Please remove this empty line

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +Example usage of CMakeBuildSucceeded to close the Vim-CMake console
Please wrap CMakeBuildSucceeded in backticks

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +
Please remove this empty line

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +      augroup vim-cmake-group
Indent all lines with a single tab character please

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +	autocmd User CMakeBuildSucceeded call cmake#console#Close()
cmake#console#Close() is not part of the user Vim-CMake API, please replace "cmake#console#Close()" with "CMakeClose"

2020-11-19 17:37 UTC, cdelledonne commented on doc/cmake.txt
> +Vim-CMake provides a set of custom events to trigger further actions. For
This paragraph is redundant here, as we already have an EVENTS section

2020-11-19 17:37 UTC, cdelledonne commented on README.md
> +Vim-CMake provides a set of custom events to trigger further actions.
Could we move this paragraph just above the "### Quickfix list" section, and make it into an "### Events" section, to match the order in doc/cmake.txt?

2020-11-19 17:37 UTC, cdelledonne commented on README.md
> +| `User CMakeBuildFailed`         | `Triggered after a failed ':CMakeBuild'` |
Only wrap command names in backticks, not the "Triggered on a successful" part

2020-11-19 18:08 UTC, cdelledonne commented on doc/cmake.txt
> +      let g:jump_on_error = 0 " We do not want to focus the console
Or I actually mean start all lines with one tab character, and add e.g. two or four spaces (or another tab character) for indented lines

2020-11-20 13:09 UTC, AlexAUT commented
Applied the requested changes :)

2020-11-20 14:57 UTC, cdelledonne approved these changes

2020-11-20 15:00 UTC, cdelledonne commented
Thanks a lot! :) 

For next time, there's no need to force-push your branch, we can always squash commits when merging. Actually separating commits might help pin-pointing the changes that were made after a review.

2020-11-20 15:00 UTC, merged